apiVersion: v1
kind: Pod
metadata:
  name: growwithsaargunam-pod
  labels:
    app: growwithsaargunam
spec:
  containers:
  - name: web
    image: nginx:alpine
    ports:
    - containerPort: 80
    volumeMounts:
    - name: html-volume
      mountPath: /usr/share/nginx/html
    resources:
      requests:
        cpu: "50m"
        memory: "32Mi"
      limits:
        cpu: "100m"
        memory: "64Mi"
  volumes:
  - name: html-volume
    configMap:
      name: web-content
