apiVersion: v1
kind: ConfigMap
metadata:
  name: web-content
data:
  index.html: |
    <html>
      <body style="text-align:center;">
        <h1 style="color:#27ae60;">Grow With Saargunam 🚀</h1>
      </body>
    </html>
